---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
dat <- read.csv("activity.csv")
dat$date <- as.Date(dat$date)
```


## What is mean total number of steps taken per day?
```{r}
totsteps <- aggregate(steps~date, dat, sum, na.rm=T)
meanspd <- mean(totsteps$steps)
mdnspd <- median(totsteps$steps)

plot(steps~date,totsteps,type="h")
abline(h=meanspd, col="blue")
abline(h=mdnspd, col="green")
legend("topleft",c("mean","median"), lwd=c(1,1),col=c("blue","green"))

paste0("Mean:   ",meanspd)
paste0("Median: ",mdnspd)
```

## What is the average daily activity pattern?
```{r}
avgsteps <- aggregate(steps~interval, dat, mean, na.rm=T)

plot(steps~interval,avgsteps,type="l")

paste0("Maximum average steps at ",avgsteps$interval[which.max(avgsteps$steps)]," interval")
```


## Imputing missing values
#### **Srategy:** Missing values for each 5-minute interval will be replaced by the mean of that 5-minute interval.

```{r}
library(plyr)

paste0("Number of missing values is  ",sum(is.na(dat$steps)), " out of ", length(dat$steps), " data")

## Use the mean of the 5-minute interval as a replacement for the missing value
dat2 <- ddply(dat,~interval,transform,steps.imputedna=replace(steps,is.na(steps),mean(steps,na.rm=T)))

summary(dat2[,c(1,4)])

totsteps2 <- aggregate(steps~date, dat2, sum, na.rm=T)
meanspd2 <- mean(totsteps2$steps)
mdnspd2 <- median(totsteps2$steps)

plot(steps~date,totsteps2,type="h")
abline(h=meanspd, col="blue")
abline(h=mdnspd, col="green")
legend("topleft",c("mean","median"), lwd=c(1,1),col=c("blue","green"))

paste0("New Mean:   ",meanspd2)
paste0("New Median: ",mdnspd2)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
dat2$weekend <- factor(ifelse(weekdays(dat2$date, abbr=T)=="Sun" | weekdays(dat2$date, abbr=T)=="Sat","weekend","weekday"))

avgsteps2 <- aggregate(steps~interval+weekend, dat2, mean, na.rm=T)

xyplot(steps~interval|weekend,avgsteps2,type="l",layout=c(1,2))
```
